name: speakin_ai
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-12.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  record: ^4.4.4
  path_provider: ^2.0.15
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.2
  audioplayers: ^4.0.0
  camera: ^0.10.5+9
  ffmpeg_kit_flutter: ^6.0.3
  ffmpeg_kit_flutter_platform_interface: ^0.2.1
  video_player: ^2.8.1
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

dependency_overrides:
  win32: ^5.10.1

  # 以下のコメントアウトされたセクションは必要に応じて使用してください
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700